# Analise o código abaixo com atenção. Sem executá-lo, preveja exatamente o
# que será impresso no final. Justifique sua resposta explicando o que acontece com a variável número e com a lista_dados dentro e fora da função.:

''' Dentro da função antes não tem alteração e depois o X vai receber o 100 e a lista vai acrescentar o 99, já fora da função antes numero vai receber 10 e a lista 1,2,3 ja depois numero permanece com 10 mas a lista acrescenta 99.
'''
